import humps
import troposphere.ssm as ssm
import troposphere.fis as fis


def build_ssm_document(name, ssm_content):
    doc = ssm.Document(name)

    doc.DocumentType = "Command"
    doc.Content = ssm_content

    return doc


def build_fis_template(name, role_arn, targets):
    doc = fis.ExperimentTemplate(name)

    # the API, at the very least, expects an empty stop condition
    none_stop_condition = fis.ExperimentTemplateStopCondition("StopCondition")
    none_stop_condition.Source = "none"

    doc.Description = "Template generated by Imp CLI."
    doc.RoleArn = role_arn
    doc.Actions = {}
    doc.StopConditions = [none_stop_condition]
    doc.Tags = {}
    doc.Targets = {
        humps.pascalize(f"fis-target-{t['name']}"): build_fis_target(t) for t in targets if "name" in t
    }

    return doc


def build_fis_target(target):
    fis_target = {}

    if "resource_type" in target:
        fis_target["ResourceType"] = target["resource_type"]

    if "selection_mode" in target:
        fis_target["SelectionMode"] = target["selection_mode"]

    if "resource_tags" in target:
        fis_target["ResourceTags"] = {
            t["key"]: t["value"] for t in target["resource_tags"]
        }

    return fis_target
