ACTION_TYPE_IMP_RUN_SCRIPT = "imp:run-script"

TAG_KEY_TEMPLATE = "CreatedByImp"
TAG_KEY_EXPERIMENT = "CreatedByImp"
TAG_KEY_RESOURCE_TYPE = "ImpResourceType"
TAG_VALUE_RESOURCE_TYPE_TEMPLATE = "template"
TAG_VALUE_RESOURCE_TYPE_AUTOMATION = "automation"
TAG_KEY_ORIGINAL_NAME = "ImpOriginalName"
