import os


class ImpRunScriptParser:
    def __init__(self, name: str, shell_script_path: str):
        self.name = name
        self.shell_script_path = shell_script_path

    def to_ssm_document(self, experiment_path: str, parameters: dict) -> dict:
        file_path = os.path.join(experiment_path, self.shell_script_path)

        full_parameters = {
            p["Key"]: {
                "description": "(Required) Auto-generated parameter for Imp CLI document.",
                "type": "String"
            } for p in parameters
        }

        with open(file_path, 'r') as stream:
            text = stream.read()
            return {
                "description": "This document was generated by Imp CLI.",
                "schemaVersion": "2.2",
                "mainSteps": [
                    {
                        "action": "aws:runShellScript",
                        "precondition": {
                            "StringEquals": ["platformType", "Linux"]
                        },
                        "name": "ImpRunShellScript",
                        "description": "Automatically generated action",
                        "inputs": {
                            "runCommand": [
                                text
                            ]
                        }
                    }
                ],
                "parameters": full_parameters
            }
